baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Web Developer Specialist and Coke Zero enthusiast extraordinaire"
theme = "toha"

[Params]
  background = 'images/bg-alt.jpg'
  copyright = "© 2020 Copyright Yeah"

  [Params.Author]
    nickname = "Jomer"
    image = "images/fjgallard.jpg"
    summary = [ 
      "I'm a Full-Stack Web developer", 
      "Feel free to explore my latest projects below",
      "While you're here, check out articles on my blog",
      "Send me a message: fjdgallardo@gmail.com"
    ]

[Newsletter]
  enable = "false"