baseURL = ""
languageCode = "en-us"
title = "Web Developer Portfolio"
theme = "toha"
publishDir = "docs"

[Params]
  background = 'images/background2.jpg'
  copyright = "© 2020 Copyright"

  [Params.Author]
    name = "Francis Jomer Gallardo"
    nickname = "Jomer"
    image = "images/fjgallard.jpg"
    photo = "images/photo.jpg"
    summary = [ 
      "Full-Stack Web Developer", 
      "Angular Developer",
      "Firebase Developer",
      "Ionic Developer",
      "Javascript Developer"
    ]
    [Params.Author.ContactInfo]
      email = "fjdgallardo@gmail.com"
      phone = "+639164266377"

[Newsletter]
  enable = "false"